# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fuzzer_pb2 as fuzzer__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fuzzer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TargetGatewayServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/aifuzzer.TargetGatewayService/Execute',
                request_serializer=fuzzer__pb2.FuzzTargetRequest.SerializeToString,
                response_deserializer=fuzzer__pb2.FuzzTargetResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/aifuzzer.TargetGatewayService/HealthCheck',
                request_serializer=fuzzer__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=fuzzer__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class TargetGatewayServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TargetGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=fuzzer__pb2.FuzzTargetRequest.FromString,
                    response_serializer=fuzzer__pb2.FuzzTargetResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=fuzzer__pb2.HealthCheckRequest.FromString,
                    response_serializer=fuzzer__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aifuzzer.TargetGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aifuzzer.TargetGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TargetGatewayService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aifuzzer.TargetGatewayService/Execute',
            fuzzer__pb2.FuzzTargetRequest.SerializeToString,
            fuzzer__pb2.FuzzTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aifuzzer.TargetGatewayService/HealthCheck',
            fuzzer__pb2.HealthCheckRequest.SerializeToString,
            fuzzer__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SemanticMutatorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MutateSemantic = channel.unary_unary(
                '/aifuzzer.SemanticMutatorService/MutateSemantic',
                request_serializer=fuzzer__pb2.SemanticMutateRequest.SerializeToString,
                response_deserializer=fuzzer__pb2.SemanticMutateResponse.FromString,
                _registered_method=True)


class SemanticMutatorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def MutateSemantic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticMutatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MutateSemantic': grpc.unary_unary_rpc_method_handler(
                    servicer.MutateSemantic,
                    request_deserializer=fuzzer__pb2.SemanticMutateRequest.FromString,
                    response_serializer=fuzzer__pb2.SemanticMutateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aifuzzer.SemanticMutatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aifuzzer.SemanticMutatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemanticMutatorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MutateSemantic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aifuzzer.SemanticMutatorService/MutateSemantic',
            fuzzer__pb2.SemanticMutateRequest.SerializeToString,
            fuzzer__pb2.SemanticMutateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
